### ISSUE TITLE
Develop feature x 

### ISSUE THREAD

**Issue by ossdhaval** [ossdhaval/gsg-event-service#2]
### Prepare
- [ ] Read contribution guidelines
- [ ] Read license information

### Task breakdown

_Please create one issue per task. Refer to [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-task-list-item) to know more._ 

- [ ] Issue for task
- [ ] Issue for task
- [ ] Issue for task
  - [ ] Issue for sub task
  - [ ] Issue for sub task

### Test cases and code coverage
- [ ] Write unit test to cover added/changed code
- [ ] Update integration tests to cover added/changed code

### Document the changes
- [ ] Issue for updating user guides if needed
- [ ] Issue for updating installation and configuration guides if needed # <issue that tracks this task>
- [ ] Issue for updating developer documentation if needed # <issue that tracks this task>
- [ ] Issue for updating technical documentation if needed # <issue that tracks this task>
